### PR TITLE
fix: check if exemption exists before cleanup

### LINKED ISSUE #463: RemoveItem is too fast for store - policies.Store.removeItem(p);
### Environment
https://github.com/defenseunicorns/uds-core/blob/7cf9c4c09dccc1d91edb7acbb2aee8750c5433ed/pepr.ts#L35 

Using the store in an atomic way is creating 422 errors when removing items. We should consider `Store.clear()` or something less transactional

reported by @zack-is-cool who also said everything seemed to be working fine but was noticing the `422` in the logs.

### PR DESCRIPTION
**Pull request by rjferguson21**
## Description
Workaround for issue where Pepr store fails to update the store perpetually if a `removeItem` is called on a key that does not exist.

FIxes https://github.com/defenseunicorns/uds-core/issues/463

## Related Issue
Fixes https://github.com/defenseunicorns/uds-core/issues/463

Relates to https://github.com/defenseunicorns/pepr/issues/865

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-template-capability/blob/main/CONTRIBUTING.md)(https://github.com/defenseunicorns/uds-template-capability/blob/main/CONTRIBUTING.md#submitting-a-pull-request) followed

### CODE REVIEW

File: pepr.ts [hunk 1]
```diff
@@ -28,11 +29,18 @@ import { prometheus } from "./src/pepr/prometheus";
     prometheus,
   ]);
   // Remove legacy policy entries from the pepr store for the 0.5.0 upgrade
-  if (process.env.PEPR_WATCH_MODE === "true" && cfg.version === "0.5.0") {
+  if (
+    process.env.PEPR_MODE === "dev" ||
+    (process.env.PEPR_WATCH_MODE === "true" && cfg.version === "0.5.0")
+  ) {
     Log.debug("Clearing legacy pepr store exemption entries...");
```
Comment (mjnagel) [inline pepr.ts:36]: Would it make sense to move this log line inside the conditional now too?

**Review by mjnagel — DISMISSED** [review]
LGTM otherwise, tested locally and seems to behave as expected.

**Review by mjnagel — APPROVED** [review]
