### PR TITLE
fix: don't add duplicate policy names to `uds-core.pepr.dev/mutated` annotation

### LINKED ISSUE #717: `annotateMutation` will add duplicate policy names to value if mutation is re-triggered
### Environment
uds-core `v0.26.1`

### Steps to reproduce
1. Apply a manifest that triggers a mutation
2. `kubectl edit/patch` the resource and remove the mutation
3. Watch the policy names get duplicated in the `uds-core.pepr.dev/mutated` annotation as the mutation gets triggered again

### Expected result
No dup policy names in the `uds-core.pepr.dev/mutated` annotation

### Actual Result
Dup policy names in the `uds-core.pepr.dev/mutated` annotation

### Visual Proof (screenshots, videos, text, etc)
```shell
$ cat ./test-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: '1Gi'
          cpu: '800m'
        requests:
          memory: '700Mi'
          cpu: '400m'
$ kubectl apply -f ./test-pod.yaml
$ kubectl get po init-demo -oyaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    uds-core.pepr.dev/mutated: '["disallow-privileged","require-non-root-user","drop-all-capabilities"]'
    uds-core.pepr.dev/uds-core-policies: succeeded
  name: init-demo
  namespace: default
...
$ kubectl edit po init-demo
***removed allowPrivilegeEscalation mutation***
$ kubectl get po init-demo -oyaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    uds-core.pepr.dev/mutated: '["disallow-privileged","require-non-root-user","drop-all-capabilities","disallow-privileged","require-non-root-user","drop-all-capabilities"]'
    uds-core.pepr.dev/uds-core-policies: succeeded
  name: init-demo
  namespace: default
```          
### Severity/Priority
low
### Additional Context
Came up as I was working https://github.com/defenseunicorns/uds-core/pull/698

### PR DESCRIPTION
**Pull request by noahpb**
## Description
Adds a check to the `annotateMutation` function that prevents duplicate values (policy names) from being added to the `uds-core.pepr.dev/mutated` key

## Related Issue
Fixes https://github.com/defenseunicorns/uds-core/issues/717

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide](https://github.com/defenseunicorns/uds-template-capability/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

File: src/pepr/policies/common.ts [hunk 1]
```diff
@@ -112,6 +112,8 @@ export function annotateMutation<T extends KubernetesObject>(
   const annotations = request.Raw.metadata?.annotations ?? {};
   const valStr = annotations[key];
   const arr = JSON.parse(valStr || "[]");
-  arr.push(transform(policy));
+  if (!arr.includes(transform(policy))) {
+    arr.push(transform(policy));
+  }
```
Comment (mjnagel) [inline src/pepr/policies/common.ts]: very nit but might be good to do a single call to transform here:
```suggestion
  const safePolicyName = transform(policy);
  if (!arr.includes(safePolicyName)) {
    arr.push(safePolicyName);
  }
```

**Review by mjnagel — APPROVED** [review]
