### PR TITLE
fix: handle legacy authservice client status

### LINKED ISSUE #1994: Authservice protected Packages may fail to reconcile in 0.48.0+
UDS Core 0.48.0 introduced support for authservice protection in ambient mode. Part of the changes to support this included changing the Package status types.

Previously `pkg.status.authserviceClients` was a list of strings, each list item being a single client ID. With 0.48.0, this was changed to a list of objects, each object containing a `clientId` field and optionally a `selector` field.

The status field is used during Package reconciliation to compare the previous state of the Package and determine if any clients were removed or changed in a way that requires additional authservice config changes or other modifications. [This code](https://github.com/defenseunicorns/uds-core/blob/v0.53.0/src/pepr/operator/controllers/keycloak/authservice/authservice.ts#L97-L159) does not account for the "old" status type, which can result in reconciliation errors in some upgrade scenarios. In the operator logs you may see an error similar to this:
```
{"level":50,"time":1759349243840,"pid":14,"hostname":"pepr-uds-core-watcher-6c6d9cc597-lsjkz","component":"operator.reconcilers","err":{"type":"Error","message":"Waypoint ID cannot be empty","stack":"Error: Waypoint ID cannot be empty\n at getWaypointName (/app/module-6c86c55d589d146012f2c8b13dae423032eaa754659e506d4fce988f93237004.js:1:25268)\n at /app/module-6c86c55d589d146012f2c8b13dae423032eaa754659e506d4fce988f93237004.js:1:40597\n at Array.map (<anonymous>)\n at purgeAuthserviceClients (/app/module-6c86c55d589d146012f2c8b13dae423032eaa754659e506d4fce988f93237004.js:1:40577)\n at authservice (/app/module-6c86c55d589d146012f2c8b13dae423032eaa754659e506d4fce988f93237004.js:1:40305)\n at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n at async reconcilePackageFlow (/app/module-6c86c55d589d146012f2c8b13dae423032eaa754659e506d4fce988f93237004.js:32:31006)\n at async packageReconciler (/app/module-6c86c55d589d146012f2c8b13dae423032eaa754659e506d4fce988f93237004.js:32:30730)\n at async Object.watchCallback (/app/node_modules/pepr/dist/lib.js:643:13)\n at async Object.watchCallback [as callback] (/app/node_modules/pepr/dist/lib.js:2422:11)"},"msg":"Error configuring uds-ui/uds-ui, maxed out retries"}
```

### PR DESCRIPTION
**Pull request by mjnagel**
## Description

This PR adds logic to handle the legacy format of the authserviceClients status field. This helps to handle some upgrade issues.

This also adds a new concept of "status migration" similar to our existing `migrate` pattern for Package spec.

## Related Issue

Fixes https://github.com/defenseunicorns/uds-core/issues/1994

## Steps to Validate

The below steps will help reproduce the issue (deploy 0.47.0, then upgrade to 0.48.0) and validate the fix (upgrade to my branch). The direct upgrade from 0.53.0 -> my branch is already validated in CI.

<details>
<summary>Deploy 0.47.0 with "legacy" status</summary>

```console
git checkout v0.47.0
# yq edits to pull from the correct flavor (zarf flavorized packages)
yq e -i '
  (.packages[] | select(.name == "core-base").ref) |= (. + "-unicorn") |
  (.packages[] | select(.name == "core-identity-authorization").ref) |= (. + "-unicorn")
' bundles/k3d-slim-dev/uds-bundle.yaml
yq e -i '
  (.packages[] | select(.name == "core-base").ref) |= (. + "-unicorn") |
  (.packages[] | select(.name == "core-identity-authorization").ref) |= (. + "-unicorn")
' bundles/base-shim/uds-bundle.yaml
uds run slim-dev --set flavor=unicorn
git restore .
kubectl apply -f src/test/app-authservice-tenant-package.yaml
kubectl get pkg -n authservice-test-app # check for ready
```

</details>

<details>
<summary>Upgrade to 0.48.0 to see issue</summary>

```console
git checkout v0.48.0
yq e -i '
  (.packages[] | select(.name == "core-base").ref) |= (. + "-unicorn") |
  (.packages[] | select(.name == "core-identity-authorization").ref) |= (. + "-unicorn")
' bundles/k3d-slim-dev/uds-bundle.yaml
yq e -i '
  (.packages[] | select(.name == "core-base").ref) |= (. + "-unicorn") |
  (.packages[] | select(.name == "core-identity-authorization").ref) |= (. + "-unicorn")
' bundles/base-shim/uds-bundle.yaml
uds run test:single-layer --set LAYER=base --set FLAVOR=unicorn # upgrades the base layer without deleting cluster
kubectl get events -n authservice-test-app
# Should see:
# Package.uds.dev "httpbin-other" is invalid: status.authserviceClients[0]: Invalid value: "string": authserviceClients[0] in body must be of type object: "string"
git restore .
 ```

</details>

<details>
<summary>Upgrade to this branch to see fix</summary>

```console
# this is a big upgrade jump, but since we're just doing the base layer it should work fine
git checkout authservice-purge-fix
# don't need the yq here because tasks work with the new flavored zarf pkgs
uds run test:single-layer --set LAYER=base --set FLAVOR=unicorn # upgrades the base layer without deleting cluster
kubectl get pkg -n authservice-test-app # check for ready
kubectl get events -n authservice-test-app # should be no new events
kubectl logs -n pepr-system deploy/pepr-uds-core-watcher | grep httpbin-other # should see it reconcile and be marked as ready
 ```

</details>

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide](https://github.com/defenseunicorns/uds-template-capability/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

File: src/pepr/operator/crd/migrate.ts [hunk 1]
```diff
@@ -39,5 +40,57 @@ export function migrate(pkg: UDSPackage) {
...
+ * - If it's a legacy string[] (client IDs), returns object[] using selectors from spec.sso
+ * - If it's already object[], returns it as-is
+ */
+export function buildMigratedAuthserviceStatus(pkg: UDSPackage): AuthserviceClient[] | undefined {
+  const raw = pkg.status?.authserviceClients as unknown;
+  if (!Array.isArray(raw) || raw.length === 0) return undefined;
+
+  const first = (raw as unknown[])[0];
+  // Already migrated
+  if (typeof first === "object") {
```
Comment (joelmccoy) [inline src/pepr/operator/crd/migrate.ts:61]: this is where i wish we were using a statically typed language here.  It would be way cooler if we could check if the type matches the current shape of the `AuthserviceClient` interface, but understand that is not possible :/

**Review by chance-coleman — APPROVED** [review]
everything worked for me in local testing

**Review by joelmccoy — APPROVED** [review]
LGTM. Tested locally.  May want to ship a quick patch release for this?
